dump-user-env: Fix error message

diff --git a/config/chroot_local-includes/usr/local/lib/dump-user-env b/config/chroot_local-includes/usr/local/lib/dump-user-env
--- a/config/chroot_local-includes/usr/local/lib/dump-user-env
+++ b/config/chroot_local-includes/usr/local/lib/dump-user-env
@@ -50,7 +50,7 @@ if [ -z "${WAYLAND_DISPLAY:-}" ]; then
   done
 fi
 if [ -z "${WAYLAND_DISPLAY:-}" ]; then
-  echo >&2 "Failed to set XAUTHORITY: No file matching /run/user/${EUID}/wayland-*"
+  echo >&2 "Failed to set WAYLAND_DISPLAY: No file matching /run/user/${EUID}/wayland-*"
   exit 1
 fi
 
