tails-backup-rsync: defensively check that we copy between mountpoints
Just in case there's some funky way to exfiltrate data e.g. by some
how managing to make $DEST a symlink. Who knows? :)

diff --git a/config/chroot_local-includes/usr/local/lib/tails-backup-rsync b/config/chroot_local-includes/usr/local/lib/tails-backup-rsync
--- a/config/chroot_local-includes/usr/local/lib/tails-backup-rsync
+++ b/config/chroot_local-includes/usr/local/lib/tails-backup-rsync
@@ -4,4 +4,9 @@
 SOURCE='/live/persistence/TailsData_unlocked/'
 DEST='/media/amnesia/TailsData/'
 
+if ! mountpoint -q "$SOURCE" || ! mountpoint -q "$DEST"; then
+    echo "error: SOURCE and DEST must be mountpoints" >&2
+    exit 1
+fi
+
 exec /usr/bin/rsync -PaSHAXv --del "$SOURCE" "$DEST"
