Be defensive about arguments.
TCA, running as the amnesia user, controls this argument, so this
would otherwise be an avenue for privilege escalation.

diff --git a/config/chroot_local-includes/usr/local/lib/tor-sandbox-helper b/config/chroot_local-includes/usr/local/lib/tor-sandbox-helper
--- a/config/chroot_local-includes/usr/local/lib/tor-sandbox-helper
+++ b/config/chroot_local-includes/usr/local/lib/tor-sandbox-helper
@@ -5,6 +5,11 @@
 # Import tor_control_getconf(), tor_control_getinfo(), tor_set_in_torrc()
 . /usr/local/lib/tails-shell-library/tor.sh
 
+if [ "${1}" != 0 ] && [ "${1}" != 1 ]; then
+    echo "error: bad argument: ${1}" >&2
+    exit 1
+fi
+
 if [ "$(tor_control_getconf Sandbox)" = "${1}" ]; then
     exit 0
 fi
