install langpacks for nightlies, too (if possible)

diff --git a/config/chroot_local-hooks/10-tbb b/config/chroot_local-hooks/10-tbb
--- a/config/chroot_local-hooks/10-tbb
+++ b/config/chroot_local-hooks/10-tbb
@@ -329,9 +329,16 @@ disable_update_checks "${TBB_INSTALL}"
 strip_nondeterminism "${TBB_INSTALL}" "${TBB_TIMESTAMP}"
 
 mkdir -p "${TBB_EXT}"
-if [ "${NIGHTLY_BUILD}" != yes ]; then
-    LANGPACKS_TARBALL="$(echo "${TBB_TARBALLS}" | grep -o "langpacks-tor-browser-linux64-.*\.tar\.xz")"
+LANGPACKS_TARBALL="$(echo "${TBB_TARBALLS}" | grep -o "langpacks-tor-browser-linux64-.*\.tar\.xz")"
+if [ -n "$LANGPACKS_TARBALL" ]; then
     install_langpacks "${TMP}/${LANGPACKS_TARBALL}" "${TBB_EXT}"
+else
+    if [ "${NIGHTLY_BUILD}" != yes ]; then
+        echo "ERROR: langpacks not found" >&2
+        exit 4
+    else
+        echo "WARNING: langpacks not found"
+    fi
 fi
 
 install_pluggable_transports "${TMP}/${MAIN_TARBALL}" /usr/bin
