Always display the 1st screen if there's any error (#18720)
If the user has a Persistent Storage and an administration password, we
can't know if they have a backup Tails already or not. Asking them to
plug it in if they don't have one will be very confusing.

The 1st screen is most important as orientation for people who might
give a shot at the application without having a backup Tails already.

For people how already have a backup Tails and might plug it in on
"Retry", I think it's good to always display them to 2nd confirmation
screen. It gives a confirmation that the initial error has been solved
and reminds that all backup data will be replaced.

diff --git a/config/chroot_local-includes/usr/local/bin/tails-backup b/config/chroot_local-includes/usr/local/bin/tails-backup
--- a/config/chroot_local-includes/usr/local/bin/tails-backup
+++ b/config/chroot_local-includes/usr/local/bin/tails-backup
@@ -39,7 +39,7 @@ EOF
 }
 
 title="$(gettext -s 'Update your backup Tails')"
-if [ ! -f "$CAN_BE_ADMINISTRATOR" ] || [ ! -d "$SOURCE" ]; then
+if [ ! -f "$CAN_BE_ADMINISTRATOR" ] || [ ! -d "$SOURCE" ] || [ ! -b "$(backup_luks_device)" ]; then
     msg="$(gettext -s 'This utility updates your backup Tails USB stick.\n\nTo create a backup Tails USB stick, see <a href="file:///usr/share/doc/tails/website/doc/first_steps/persistence/backup.en.html">making a backup of your Persistent Storage</a>.\n\n<b>Impossible to update your backup Tails.</b>\n\nTo update your backup Tails, you need to:')"
     if [ ! -d "$SOURCE" ]; then
         msg="${msg}""$(gettext -s '\n\n• Unlock your Persistent Storage when starting Tails.')"
@@ -47,24 +47,31 @@ if [ ! -f "$CAN_BE_ADMINISTRATOR" ] || [ ! -d "$SOURCE" ]; then
     if [ ! -f "$CAN_BE_ADMINISTRATOR" ]; then
         msg="${msg}""$(gettext -s '\n\n• Set up an <a href="file:///usr/share/doc/tails/website/doc/first_steps/welcome_screen/administration_password.en.html">administration password</a> when starting Tails.')"
     fi
-    zenity --error --ellipsize --title "$title" --text "$msg"
-    exit 1
+    if [ ! -b "$(backup_luks_device)" ]; then
+        msg="${msg}""$(gettext -s '\n\n• Plug in your backup Tails USB stick.')"
+    fi
+    # Ask to retry if only the backup Tails USB stick is missing
+    if [ ! -b "$(backup_luks_device)" ] && [ -f "$CAN_BE_ADMINISTRATOR" ] && [ -d "$SOURCE" ]; then
+        while [ ! -d "$DEST" ]; do
+            if [ -b "$(backup_luks_device)" ]; then
+                pinentry_auth "$(gettext -s '')" "$(gettext -s 'Enter the passphrase for your backup Tails USB stick')" \
+                    | gio mount --device "$(backup_luks_device)"
+            else
+                if ! zenity --question --ellipsize --title "$title" --text "$msg" --ok-label "$(gettext -s 'Retry')" --cancel-label "$(gettext -s 'Cancel')"; then
+                    exit 1
+                fi
+            fi
+        done
+    else
+        zenity --error --ellipsize --title "$title" --text "$msg"
+        exit 1
+    fi
 fi
 
 msg="$(gettext -s 'Do you want to update your backup Tails USB stick now?\n\nThis will replace all data in the Persistent Storage of your backup Tails.')"
 if ! zenity --question --ellipsize --title "$title" --text "$msg" --ok-label "$(gettext -s 'Update')" --cancel-label "$(gettext -s 'Cancel')" ; then
     exit 1
 fi
-
-while [ ! -d "$DEST" ]; do
-    if [ -b "$(backup_luks_device)" ]; then
-        pinentry_auth "$(gettext -s '')" "$(gettext -s 'Enter the passphrase for your backup Tails USB stick')" \
-            | gio mount --device "$(backup_luks_device)"
-    else
-        msg="$(gettext -s 'Please plug in your backup Tails USB stick!')"
-        zenity --info --ellipsize --title "$title" --text "$msg"
-    fi
-done
 
 # Run real backup command. This requires privileges.
 if pkexec /usr/bin/rsync -PaSHAXv --del "$SOURCE" "$DEST" | zenity --progress --pulsate --auto-close --no-cancel; then
