Revert "Welcome Screen: always enable the Unsafe Browser and make the setting obsolete"
This reverts commit e099de59e423001726389ccc23eda1773f92e7ff.

refs #19289

diff --git a/config/chroot_local-includes/usr/local/sbin/unsafe-browser b/config/chroot_local-includes/usr/local/sbin/unsafe-browser
--- a/config/chroot_local-includes/usr/local/sbin/unsafe-browser
+++ b/config/chroot_local-includes/usr/local/sbin/unsafe-browser
@@ -16,6 +16,9 @@ export TEXTDOMAIN
 # Import setup_chroot_for_browser() and configure_chroot_browser().
 . /usr/local/lib/tails-shell-library/chroot-browser.sh
 
+# Import unsafe_browser_is_enabled and persistence_is_enabled
+. /usr/local/lib/tails-shell-library/tails-greeter.sh
+
 # Import nm_is_connected
 . /usr/local/lib/tails-shell-library/network.sh
 
@@ -65,6 +68,32 @@ $(gettext "The Unsafe Browser is not anonymous and the websites that you visit c
     fi
 }
 
+exit_because_disabled() {
+    local msg restart cancel confirm_msg confirm_button
+    msg="$(gettext "The Unsafe Browser was not enabled in the Welcome Screen.\n\n\
+To <a href='file:///usr/share/doc/tails/website/doc/anonymous_internet/unsafe_browser.en.html#use'>use the Unsafe Browser</a>, restart Tails and enable \
+the Unsafe Browser in the additional settings of the Welcome Screen.")"
+    # Only mention the Persistent Storage if there is one (see #18551)
+    if persistence_is_enabled; then
+	msg="${msg}""$(gettext "\n\nTo always enable the Unsafe Browser, turn on the Welcome Screen feature of the Persistent Storage.")"
+    fi
+
+    restart="$(gettext "_Restart")"
+    cancel="$(gettext "_Cancel")"
+    confirm_msg="$(gettext "Do you really want to restart Tails now?\n\nAll your current work will be lost.")"
+    confirm_button="$(gettext "Restart Now")"
+    if _zenity --question --ellipsize --title "" --text "${msg}" --icon-name="dialog-error" \
+               --ok-label "${restart}"  --cancel-label "${cancel}" --default-cancel \
+       && \
+       _zenity --question --width=300 --title "" --text "${confirm_msg}" \
+               --ok-label "${confirm_button}" --cancel-label "${cancel}" --default-cancel
+    then
+        /sbin/reboot || error "$(gettext "Failed to restart the system.")"
+    fi
+
+    exit 1
+}
+
 show_start_notification () {
     local title body
     title="$(gettext "Starting the Unsafe Browser...")"
@@ -95,6 +124,9 @@ else
     WARNING_PAGE='/usr/share/doc/tails/website/misc/captive_portal_warning'
 fi
 HOME_PAGE="$(localized_tails_doc_page "${WARNING_PAGE}")"
+
+# Check if the Unsafe Browser was disabled in the startup options
+unsafe_browser_is_enabled || exit_because_disabled
 
 # Prevent multiple instances of the script.
 exec 9>"${LOCK}"
