Add to confirm before restarting (#18912)

diff --git a/config/chroot_local-includes/usr/local/sbin/unsafe-browser b/config/chroot_local-includes/usr/local/sbin/unsafe-browser
--- a/config/chroot_local-includes/usr/local/sbin/unsafe-browser
+++ b/config/chroot_local-includes/usr/local/sbin/unsafe-browser
@@ -63,12 +63,17 @@ the Unsafe Browser in the additional settings of the Welcome Screen.")"
 	if  sudo -u "${SUDO_USER}" \
          zenity --question --ellipsize --title "" --text "${msg}" --icon-name="dialog-error" \
                 --ok-label "${restart}"  --cancel-label "${close}"; then
-            if ! /sbin/reboot; then
-		error "$(gettext "Failed to restart the system.")"
-	    fi
-	else
-	    exit 1
-	fi
+            msg="$(gettext "Do you really want to restart Tails now?\n\nAll your current work will be lost.")"
+            confirm="$(gettext "Restart Now")"
+            if sudo -u "${SUDO_USER}" \
+               zenity --warning --width=300 --title "" --text "${msg}" --ok-label "${confirm}"; then
+                if ! /sbin/reboot; then
+                    error "$(gettext "Failed to restart the system.")"
+                fi
+            fi
+        else
+            exit 1
+        fi
     fi
 }
 
